version: '2'

services:


  #################################
  # Kafka & Zookeeper for Streaming
  #################################
  
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeperLocal
    ports:
      - "2181:2181"
    networks:
      - zkk
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      
  kafka:
    image: wurstmeister/kafka
    container_name: kafkaLocal
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    networks:
      - zkk
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "device-data-live:1:1,device-data-test:1:1,device-data-alert:1:1"



networks:
  zkk:


  
